2021-08-05 13:23:55,491 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:55,493 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:56,153 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:56,154 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:56,158 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:56,159 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:56,818 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:56,819 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:56,823 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:56,824 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:57,446 --- tutorial.helper - WARNING - This is a warning
