2021-08-05 13:23:52,407 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:52,408 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:52,412 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:52,413 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:53,045 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:53,045 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:53,050 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:53,050 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:53,700 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:53,700 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:53,705 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
