2021-08-05 13:23:50,348 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:50,353 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:50,354 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:51,053 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:51,053 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:51,058 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:51,058 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:51,742 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:51,743 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:51,747 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:51,748 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

